- hosts: all
  gather_facts: true
  become: true
  vars:
    network: <задать имя сети docker>
    dst: <задать имя директории где будут храниться файлы>
  roles:
  - role: kafka
    tags: kafka
  - role: elastic
    vars:
      container_cpulimit: "2"
      container_memlimit: "512m"
      container_memlimit_service: "256m"
      cluster_name: "es-cluster"
    tags: elastic
  - role: tgbot
    vars:
      token: <задать token>
      chat_id: <задать id разрешнных пользователей>
      my_docker_image_name: tgbot
    tags: tgbot